platform:ios,'9.0'
target 'ShopProject' do
use_frameworks!
    pod 'SnapKit'
    pod 'Kingfisher'
    pod 'ESTabBarController-swift'
    pod 'FSPagerView'
    pod 'Moya'
    pod 'HandyJSON', '5.0.0-beta'
    pod 'SwiftyJSON'
    pod 'DNSPageView'
    pod 'JXMarqueeView'
    pod 'LTScrollView'
    pod 'MJRefresh'
    #pod 'SkeletonView'
    pod 'SwiftMessages'
    
    #pod 'YYKit'
    pod 'SVProgressHUD'
    pod 'StreamingKit'
    pod 'ObjectMapper'
    pod 'ESPullToRefresh'
#    pod 'RealmSwift'
#    pod 'Realm'
#    pod 'GRDB.swift'
    pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
    pod 'WCDB.swift'
end
